### ISSUE TITLE
bad cpu type

### ISSUE THREAD

**Issue by leeyxq** [ops-xu/alfred-workflow-message-code#1]
: line 1: ./main: Bad CPU type in executable， please fix，😄

**Comment by 0x0021** [comment]
大哥没考虑intel的U呀

**Comment by ops-xu** [comment]
[下载最新的amd64试试](https://github.com/ops-xu/alfred-workflow-message-code/releases/tag/v1.0.1)
第一次写go, 不知道需要交叉编译.
